name: import-solution.zip
# Import Managed Solution 

on:
  workflow_dispatch:
    
env:
#edit your values here
  ENVIRONMENT_URL: 'https://org7e342b1b.crm8.dynamics.com'
  CLIENT_ID: 'ebc9a79c-d471-4dfc-bb07-d6bbdc6e5392'
  TENANT_ID: 'e0746178-dab3-42b8-b472-9f60695cb522'

jobs:
  import-solution-zip:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    # env:
    #   RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    
     - name: Import solution to Dataverse Environment
        uses: microsoft/powerplatform-actions/import-solution@0.4.0
        with:
          environment-url: ${{env.ENVIRONMENT_URL}}
          app-id: ${{env.CLIENT_ID}}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{env.TENANT_ID}}
          solution-file: Solutions/NorthWindDataModelSchema_1_0_0_1_managed.zip
          force-overwrite: true
          publish-changes: true