# This is a basic workflow to import Solution in Power Platform Environment

name: deploy-Solution

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Deploy 
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          lfs: true
      
      # Import using Power Platform CLI build tools
      - uses: microsoft/powerplatform-actions/import-solution@0.4.0
        with:
          environment-url: ${{env.ENVIRONMENT_URL}}
          app-id: ${{env.CLIENT_ID}}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{env.TENANT_ID}}
          solution-file: Solutions/NorthWindDataModelSchema_1_0_0_1_managed.zip
          force-overwrite: true
          publish-changes: true
